//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Translation Aggregator.rc
//
#define IDAPPLY                         3
#define ID_ADD                          4
#define ID_DELETE                       5
#define ID_CLEAR                        6
#define IDR_MAIN_MENU                   102
#ifdef SETSUMI_CHANGES
#define IDC_POINTER                     104
#endif
#define IDR_ACCELERATORS                105
#define IDI_ICON1                       106
#define IDR_TOOLBAR_TRANSLATION         107
#define IDD_ATLAS_CONFIG                109
#define IDD_INJECT_DIALOG               110
#define IDD_MECAB_CONFIG                111
#define IDD_WWWJDIC_CONFIG              112
#define IDD_JPARSER_CONFIG              113
#define IDD_OPTIONS_DIALOG              114
#define IDD_CONTEXT_MANAGER             115
#define IDR_MENU_CONTEXT_MANAGER        117
#define IDD_AGTH_CONVERSION_TOOL        118
#define IDC_DEFAULT_COLOR               1000
#define IDC_PICK_DEFAULT_COLOR          1001
#define IDC_ELLIPSES                    1001
#define IDC_FURIGANA_COLOR              1002
#define IDC_COMMAS                      1002
#define IDC_PICK_FURIGANA_COLOR         1003
#define IDC_QUOTES                      1003
#define IDC_PARTICLE_COLOR              1004
#define IDC_DOUBLE_QUOTES               1004
#define IDC_PICK_PARTICLE_COLOR         1005
#define IDC_PARENTHESES                 1005
#define IDC_TRANSLATION_COLOR           1006
#define IDC_SQUARE_BRACKETS             1006
#define IDC_PICK_TRANSLATION_COLOR      1007
#define IDC_SINGLE_LINE_BREAKS          1007
#define IDC_KANJI_COLOR                 1008
#define IDC_ENVIRONMENT                 1008
#define IDC_PICK_KANJI_COLOR            1009
#define IDC_PROCESS_LIST                1009
#define IDC_RULE_SET                    1009
#define IDC_HIRAGANA_COLOR              1010
#define IDC_CONTEXT_LIST                1010
#define IDC_PICK_HIRAGANA_COLOR         1011
#define IDC_PAREN_COLOR                 1012
#define IDC_EXE_PATH                    1012
#define IDC_PICK_PAREN_COLOR            1013
#define IDC_BROWSE                      1013
#define IDC_CONJ_COLOR                  1014
#define IDC_PROFILE_NAME                1014
#define IDC_PICK_CONJ_COLOR             1015
#define IDC_NO_HOOK                     1015
#define IDC_AGTH                        1016
#define IDC_INTERNAL_HOOK               1017
#define IDC_BROWSE2                     1018
#define IDC_CREATE_SHORTCUT             1018
#define IDC_TRANSLATE_MENUS             1019
#define IDC_HIRAGANA                    1019
#define IDC_NEW_PROECSS                 1020
#define IDC_CONFIG_ATLAS                1020
#define IDC_KATAKANA                    1020
#define IDC_ROMAJI                      1021
#define IDC_NO_FURIGANA                 1022
#define IDC_CLIPBOARD_COPY              1022
#define IDC_DCBS_OVERRIDE               1023
#define IDC_LOG_TRANSLATIONS            1024
#define IDC_INTERNAL_DEFAULT_HOOKS      1025
#define IDC_INTERNAL_DEFAULT_FILTERS    1026
#define IDC_INJECT_CHILDREN             1027
#define IDC_INJECT_CHILDREN_SAME_SETTINGS 1028
#define IDC_CHECK_INTERNAL_CODES        1029
#define IDC_AGTH_CODE_CONVERSION_TOOL   1030
#define IDC_NORMAL_FONT_SIZE            1032
#define IDC_FURIGANA_FONT_SIZE          1033
#define IDC_APPLY                       1034
#define IDC_WWWJDICT_MIRROR_COMBO       1035
#define IDC_DISPLAY_VERB_CONJUGATIONS   1036
#define IDC_JAPANESE_OWN_LINE           1037
#define IDC_SINGLE_KANJI                1038
#define IDC_OLD                         1038
#define IDC_DEFINITION_LINES            1038
#define IDC_SINGLE_HIRAGANA             1039
#define IDC_REPLACE                     1039
#define IDC_NUMBER_REFORMAT             1039
#define IDC_USE_MECAB                   1040
#define IDC_AUTODETECT_PROCESS          1040
#define IDC_INJECT_PROCESS              1041
#define IDC_SUBSTITUTION_LIST           1041
#define IDC_NEW_PROCESS                 1042
#define IDC_HIDE_CROSS_REFS             1043
#define IDC_HIDE_POS                    1044
#define IDC_HIDE_POS2                   1045
#define IDC_HIDE_USAGE                  1045
#define IDC_NO_KANA_BRACKETS            1046
#define IDC_AGTH_CODE                   1057
#define IDC_TA_CODE                     1058
#define IDC_ADD                         1059
#define IDC_COMBO1                      1060
#define IDC_CB_LOCALE                   1060
#define IDC_AGTH_REMOVE_REPEATED_SYMBOLS 1061
#define IDC_AGTH_REPEATED_COUNT         1062
#define IDC_CONTEXT_DISABLE2            1062
#define IDC_AGTH_REMOVE_REPEATED_SYMBOL_COUNT 1063
#define IDC_AGTH_PARAMS_ADDED           1064
#define IDC_AGTH_REMOVE_REPEATED_PHRASES 1065
#define IDC_AGTH_REMOVE_REPEATED_PHRASE_COUNT 1066
#define IDC_AGTH_REMOVE_REPEATED_PHRASE_COUNT2 1067
#define IDC_AGTH_ADD_PARAMS             1068
#define IDC_AGTH_ACTUAL_PARAMS          1069
#define IDC_INTERNAL_IDLE_DELAY         1070
#define IDC_INTERNAL_HOOKS              1071
#define IDC_MAX_HISTORY                 1071
#define IDC_CONTEXT_FULL_HISTORY        1072
#define IDC_INJECTION_DELAY             1072
#define IDC_HOOK_DELAY                  1072
#define IDC_CONTEXT_INSTA_MERGE         1147
#define IDC_CONTEXT_FLUSH_MERGE         1148
#define IDC_CONTEXT_TEXT                1149
#define IDC_CONTEXT_AUTO_TRANSLATE      1150
#define IDC_CONTEXT_DISABLE             1151
#define IDC_CHAR_REPEAT_AUTO_CONSTANT   1152
#define IDC_CHAR_REPEAT_NONE            1153
#define IDC_CHAR_REPEAT_INFINITE        1154
#define IDC_CHAR_REPEAT_AUTO_ADVANCED   1155
#define IDC_CHAR_REPEAT_CUSTOM          1156
#define IDC_PHRASE_REPEAT_AUTO          1157
#define IDC_PHRASE_REPEAT_NONE          1158
#define IDC_PHRASE_REPEAT_CUSTOM        1159
#define IDC_TEXT_LOOPS                  1160
#define IDC_LINE_BREAK_REMOVE           1161
#define IDC_LINE_BREAK_KEEP             1162
#define IDC_LINE_BREAK_KEEP_SOME        1163
#define IDC_JAPANESE_ONLY               1164
#define IDC_PHRASE_EXTENSION_NONE       1165
#define IDC_PHRASE_EXTENSION_BASIC      1166
#define IDC_PHRASE_EXTENSION_AGGRESSIVE 1167
#define IDC_AUTO_CLIPBOARD              1168
#define IDC_CHAR_REPEAT_CUSTOM_TEXT     1169
#define IDC_LINE_BREAK_FIRST            1170
#define IDC_LINE_BREAK_LAST             1171
#define IDC_PHRASE_REPEAT_CUSTOM_MIN    1172
#define IDC_PHRASE_REPEAT_CUSTOM_MAX    1173
#define IDC_HOOK_PORT                   1300
#define ID_FILE_QUIT                    40001
#define ID_VIEW_TWOCOLUMN               40002
#define ID_TRANSLATE                    40003
#define ID_TRANSLATE_ALL                40004
#define ID_SEARCH_DICT                  40005
#define ID_SLOW1                        40006
#define ID_SLOW2                        40007
#define ID_SLOW3                        40008
#define ID_SLOW4                        40009
#define ID_SLOW5                        40010
#define ID_SLOW6                        40011
#define ID_SLOW7                        40012
#define ID_AUTO_CLIPBOARD               40013
#define ID_AUTOCLIPBOARD                40014
#define ID_VIEW_SHOWALL                 40015
#define ID_CLOSE_TRANSLATION            40018
#define ID_ATLAS_TRANSLATION_EDITOR     40019
#define ID_FILE_OPTIONS                 40020
#define ID_VIEW_FONT                    40021
#define ID_CONFIG                       40022
#define ID_TOPMOST                      40024
#define ID_VIEW_LOCKORDER               40025
#define ID_LAYOUT_0                     40026
#define ID_LAYOUT_1                     40027
#define ID_LAYOUT_2                     40028
#define ID_LAYOUT_3                     40029
#define ID_LAYOUT_4                     40030
#define ID_LAYOUT_5                     40031
#define ID_LAYOUT_6                     40032
#define ID_LAYOUT_7                     40033
#define ID_LAYOUT_8                     40034
#define ID_LAYOUT_9                     40035
#define ID_BIND_LAYOUT_0                40036
#define ID_BIND_LAYOUT_1                40037
#define ID_BIND_LAYOUT_2                40038
#define ID_BIND_LAYOUT_3                40039
#define ID_BIND_LAYOUT_4                40040
#define ID_BIND_LAYOUT_5                40041
#define ID_BIND_LAYOUT_6                40042
#define ID_BIND_LAYOUT_7                40043
#define ID_BIND_LAYOUT_8                40044
#define ID_BIND_LAYOUT_9                40045
#define ID_VIEW_HIDETOOLBAR             40046
#define ID_VIEW_HIDEWINDOWFRAME         40047
#define ID_FILE_LAUNCHPROCESS           40050
#define ID_FILE_ATTACHTOPROCESS         40051
#define ID_FILE_INJECTINTOPROCESS       40052
#define ID_VIEW_LESSSOLID               40055
#define ID_VIEW_MORESOLID               40056
#define ID_PROGRAMTRANSLATION_FULLTRANSLATION 40057
#define ID_TRANS_HIGHLIGHTED            40058
#define ID_VIEW_ALWAYSONTOP             40062
#define ID_TO_HIRAGANA                  40064
#define ID_TO_KATAKANA                  40065
#define ID_TO_ROMAJI                    40066
#define ID_SJIS_TO_HEX                  40067
#define ID_UTF16_TO_HEX                 40068
#define ID_HEX_TO_SJIS                  40069
#define ID_HEX_TO_UTF16                 40070
#define ID_TOOLS_OPTIONS                40071
#define ID_TOOLS_AUTOCONVERTHALFWIDTHJAPANESE 40072
#define ID_TOOLS_AUTOCONVERT            40073
#define ID_TOOLS_SUBSTITUTIONSENABLED   40074
#define ID_TOOLS_ENABLESUBSTITUTIONS    40075
#define ID_TOOLS_AUTOCONVERTTOHIRAGANAWHENNOJAPANESE 40076
#define ID_TOOLS_AUTOCONVERTHIRAGANA    40077
#define ID_TOOLS_AUTOCONVERT_HIRAGANA   40078
#define ID_TOOLS_MANAGEATTACHEDCONTEXTS 40079
#define ID_TOOLS_MANAGECONTEXTS         40080
#define ID_PROCESS_DESTROYCONTEXTS      40083
#define ID_CONTEXT_CLEARHISTORY         40084
#define ID_CONTEXT_CLEAR                40085
#define ID_PROCESS_CLEAR                40086
#define ID_VIEW_TOOLTIP_FONT            40087
#ifdef SETSUMI_CHANGES
#define ID_BORDERLESS_WINDOW            40088
#define ID_VIEW_RESETPLACEMENT          40091
#endif
#define ID_HISTORY_BACK                 40088
#define ID_HISTORY_FORWARD              40089
#define ID_TOOLS_PREVIOUSHISTORYENTRY   40091
#define ID_TOOLS_NEXTHISTORYENTRY       40092
#define ID_HISTORY_NEXT                 40093
#define ID_FILE_GLOBALHOTKEYSCTRL       40094
#define ID_FILE_GLOBALHOTKEYS           40095

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        119
#define _APS_NEXT_COMMAND_VALUE         40096
#define _APS_NEXT_CONTROL_VALUE         1061
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
